name: expenwall_mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_sign_in: ^6.2.2
  googleapis: ^13.2.0
  http: ^1.2.2
  path_provider: ^2.1.5
  intl: ^0.19.0
  shared_preferences: ^2.3.3
  uuid: ^4.5.1
  workmanager: ^0.5.2
  google_mlkit_text_recognition: ^0.15.0
  image_picker: ^1.1.2
  camera: ^0.11.0+2
  archive: ^3.6.1
  pdf: ^3.10.8
  printing: ^5.12.0
  fl_chart: ^0.69.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
